version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
    ports:
      - 3900:9000
    volumes:
      - ./tmp/s3/storage:/data
