name: Test
on: [push, pull_request]
jobs:
  test:
    services:
      minio:
        image: minio/minio:RELEASE.2020-10-28T08-16-50Z
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: YCAJEDz8XlzfZ0ZQPnPSENsJT
          MINIO_SECRET_KEY: YCM5kzzpp388VAjr5tkos4kWvFnomVFw33LfoEHn
        options: --name=minio --health-cmd "curl http://localhost:9000/minio/health/live"
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: wget https://dl.min.io/client/mc/release/linux-amd64/mc
      - run: chmod +x ./mc
      - run: ./mc alias set minio http://127.0.0.1:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}
      - run: ./mc mb --ignore-existing minio/upstorage
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go vet ./...
      - run: go test ./...
        env:
          S3_HOST: http://localhost:9000
          S3_ACCESS_KEY: NAUBWE2PZUNCEHLH2I3P
          S3_SECRET_KEY: EUWVAfkRoA8KE/JrrsDW3/gmehNgj29Lm8iFPckB
          S3_BUCKET: upstorage
